READY FOR REVIEW: renamed binding to link everywhere
wascc/wasmCloud pull request #12
Opened 2020-11-14 12:23 UTC by mikezupper

all binding references were renamed to link.

2020-11-16 15:41 UTC, autodidaddict requested changes

2020-11-16 15:41 UTC, autodidaddict commented on crates/wascc-host/src/auth.rs
> +            link: "default".to_string(),
This should be `link_name` here.

2020-11-16 15:41 UTC, autodidaddict commented on crates/wascc-host/src/capability/native_host.rs
> +            link: state.cap.link_name.to_string(),
Field name should be `link_name` on the WasccEntity::Capability variant

2020-11-17 20:17 UTC, brooksmtownsend approved these changes
LGTM

2020-11-18 19:12 UTC, autodidaddict commented
Same as with the other PR, I think it makes sense to wait until #14 is done and then re-apply this change to main rather than attempting the merge conflict resolution since that PR basically makes changes everywhere.

2020-12-02 18:53 UTC, autodidaddict commented
@mikezupper if you want you can try and resolve the conflicts here, or I can just try and do a by-hand merge offline. I tried to get git to do this for me automatically and it laughed at my weakness.

2020-12-03 13:57 UTC, mikezupper commented
i will recreate a new PR with these changes. Too many files have been renamed or altered beyond GITs ability to reconcile the differences.

2020-12-03 13:57 UTC, closed without merging